weblog/config/routes.rb
Rails.application.routes.draw do

  devise_for :users , controllers: {registrations: :registrations}

root 'posts#index'
resources "users"
resources "posts" do
  resources "commentaires"
end

end

weblog/app/models/commentaire.rb
class Commentaire < ActiveRecord::Base
belongs_to :post
belongs_to :user
end

weblog/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :commentaires
  belongs_to :user
  mount_uploader :vignette, PostUploader
end

weblog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable
    has_many :posts
    has_many :commentaires
end

weblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

weblog/app/controllers/commentaires_controller.rb
class CommentairesController < ApplicationController
  before_action :load_post 

    def index
      @commentaire = @p.commentaires
    end

    def create
      @c = Commentaire.new(comment_params)
      @c.user = current_user
      @c.post = @p
      if @c.save
          redirect_to post_path(@p)
      else
          render "new"
      end
    end

    def new
      @c = Commentaire.new
    end

  #  def update
  #    if @c.update_attributes(comment_params)
  #        redirect_to user_photo_path(@u,@p)
  #    else
  #        render "pas po"
  #    end
  #  end

    def destroy
      @c.destroy
      redirect_to post_path(@p)
    end

    def comment_params
      params.require(:commentaire).permit(:name,:user_id,:post_id)
    end

    def load_comment
      Commentaire.find(params[:id])
    end

    def load_user
      @u=current_user
    end

    def load_post
      @p=Post.find(params[:post_id])
    end

end

weblog/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

weblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :load_post, only:[:show,:update,:edit,:destroy,:load_user]
    before_action :load_user

  def index
    @p = Post.order('created_at DESC')

  end

  def create
    @p = Post.new(post_params)
    @p.user=@u
    if @p.save
        redirect_to post_path(@p)
    else
        render "new"
    end
  end

  def new
    @p=Post.new

  end

  def update
    if @p.update_attributes(post_params) && @p.user == current_user
        redirect_to post_path(@p)
    else
        render "404"
    end
   end

  def destroy
    @p.destroy
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:titre,:chapeau,:vignette,:user_id)
  end

  def load_post
    @p=Post.find(params[:id])
  end
  def load_user
    @u=current_user #essayez de load user courant
  end
end

weblog/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def sign_up_params
      params.require(:user).permit(:email,:password,:password_confirmation,:firstname,:lastname,:pseudo)
  end
end

weblog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only:[:show,:update,:edit,:destroy]
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def create
    @u = User.new(user_params)
    if @u.save
        redirect_to root_path
    else
        render "new"
    end
  end

  def new
    @u=User.new
  end

  def update
    if @u.update_attributes(user_params)&& (@u == current_user)
        redirect_to user_path(@u)
    else
        render "404"
    end
  end

  def destroy
    @u.destroy
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:pseudo,:firstname,:lastname)
  end

  def load_user
    @u=User.find(params[:id])
  end

end

weblog/app/helpers/application_helper.rb
module ApplicationHelper
end

weblog/app/helpers/commentaires_helper.rb
module CommentairesHelper
end

weblog/app/helpers/home_helper.rb
module HomeHelper
end

weblog/app/helpers/posts_helper.rb
module PostsHelper
end

weblog/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

weblog/app/helpers/users_helper.rb
module UsersHelper
end

weblog/app/views/commentaires/new.html.erb
<%=form_for @c, url:[@p,@c] do |f|%>

  <label>Votre Commentaire : </label><br />
  <%=f.text_area "text"%>
    <%=@c.errors.messages[:text].to_sentence%><br/>

<br />
  <%=f.submit%>
<%end%>

weblog/app/views/home/index.html.erb
<p>Bienvenue sur Blog Ruby.</p>

weblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog Ruby</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div id="title">
    <h1>BR</h1>
  </div>
  <h2><%= link_to "BLOG RUBY", root_path%></h2>
    <div id="connection_interface">
    <%- if user_signed_in? %>
      <p>Connecté</p>
      <p><%=link_to "Voir Profil",user_path(current_user)%></p>
      <p> <%=link_to "Se déconnecter",destroy_user_session_path,:method => :delete%></p>
    <%-else%>
    <p>Deconnecté <%=link_to "Se connecter",user_session_path %></p>
    <%-end%>
  </div>
  </header>
<%= yield %>

</body>
</html>

weblog/app/views/posts/_form.html.erb
<%=form_for @p do |f|%>

  <label>Titre : </label>
  <%=f.text_field "titre"%>
    <%=@p.errors.messages[:titre].to_sentence%><br/>

  <%=f.text_area "chapeau"%>
      <%=@p.errors.messages[:chapeau].to_sentence%><br/>

  <label>Vignette : </label>
  <%=f.file_field :vignette%>

<<br />
  <%=f.submit%>
<%end%>

weblog/app/views/posts/edit.html.erb
<h2>Modification de Post</h2>
<%= render partial: "form" %>

weblog/app/views/posts/index.html.erb
<h1><u>Posts</u></h1>
<%- if user_signed_in? %>
<%= link_to " Noveau Post",new_post_path%>
<%- end%>
<br />
<%= @p.count %> Posts  <br />
<%- @p.each do |post|%>
<br />
<p> <%= image_tag post.vignette.thumb%>
   <%= link_to post_path(post) do
        post.titre
      end%>
  </p>



    <br>
<%-end%>

weblog/app/views/posts/new.html.erb
<h2>Nouveau Post</h2>
<%= render partial: "form" %>

weblog/app/views/posts/show.html.erb
<p><%= image_tag @p.vignette.small%></p>
Nom : <%=@p.titre%> <br/>
Auteur : <i>
<%=if User.exists?(@p.user_id)
    link_to user_path(@p.user_id) do
        User.find(@p.user_id).pseudo
      end
    else
      "Utilisateur supprimé"
    end%>
  </i>
    <br/>
Texte :<%=@p.chapeau%>

<%- if @u != nil%>
  <%- if @p.user_id == @u.id %>
  <br />
    <%= link_to " Modifier Post ", edit_post_path%><br>
      <%= link_to " Supprimer Post ", post_path(@p),method: :delete , data: {confirm: "Etes vous sur?"}%><br>
    <%-end%>
    <br />


<%-end%>

weblog/app/views/users/show.html.erb
Pseudo : <%=@u.pseudo%><br/>
Prénom : <%=@u.firstname%> <br/>
Nom : <%=@u.lastname%><br/>
Email : <%=@u.email%><br />
<%-if @u == current_user%>
<%= link_to "Supprimer l'utilisateur", user_path(@u),method: :delete , data: {confirm: "Etes vous sur?"}%>
<%-end%>
<br/>
Posts :
<%- @u.posts.each do |post|%>
<br />
<p> <%= image_tag post.vignette.thumb%>
   <%= link_to post_path(post) do
        post.titre
      end%>
  </p>
    <br>

<%-end%>